[package]
name = "quantum-graphsim"
version = "0.0.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "graphsim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
rand = "0.9.2"
